#!/bin/sh

INSTALL_DIR="/usr/local/spkrepo"
CFG_FILE="${INSTALL_DIR}/SpkRepo.SelfHost.exe.config"

ln -s ${SYNOPKG_PKGDEST} ${INSTALL_DIR}

sed -i -e "s|App_Data|${wizard_package_dir:=/volume1/public/packages}|g" ${CFG_FILE}